require: rubocop-rspec

AllCops:
  Exclude:
    - vendor/**/*
  TargetRubyVersion: 2.5

Gemspec/RequiredRubyVersion:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Naming/FileName:
  Exclude:
    - lib/omniauth-paypal-oauth2.rb

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets
